server:
  applicationConnectors:
    - type: http
      port: 9292
  adminConnectors:
    - type: http
      port: 9293

# Logging settings.
logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO
  appenders:
    - type: console
#    - type: file
#      currentLogFilename: ./xwcps.log
#      threshold: ALL
#      archive: true
#      archivedLogFilenamePattern: ./xwcps-%d.log
#      archivedFileCount: 5
#      timeZone: UTC
